
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/Genshin
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - mern-app
    depends_on:
      - mongo

  frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      restart: unless-stopped  
      env_file: ./frontend/.env
      volumes:
        - ./frontend:/app
        - /app/node_modules
      networks:
        - mern-app
      ports:
        - 5173:5173
      depends_on:
        - api



volumes:
  mongo_data:

networks:
  mern-app:
    driver: bridge

